### ISSUE TITLE
Not able to run mnist code example

### ISSUE THREAD

**Issue by dvigneshwer** [tedsta/deeplearn-rs#5]
![image](https://cloud.githubusercontent.com/assets/5075497/26772672/91449168-49e4-11e7-8168-efa9c763e40c.png)

PFB the set of instructions:

~~~~
git clone https://github.com/tedsta/deeplearn-rs.git
cd deeplearn-rs
sh download_mnist.sh
cargo run --example mnist
~~~~

Let me know the way correct steps to run the code.

**Comment by tedsta** [comment]
Ah, it looks like `std::marker::Reflect` was recently removed. I think `gpuarray-rs` only uses it for `TypeId::of<T>`, which no longer requires `T` to be `Reflect`. I'll fix it tonight. Thanks for the catch!

Note that this crate was completely an experiment and a learning exercise and isn't actively maintained anymore. The OpenCL kernels in `gpuarray-rs` are not as fast as they could be. For instance, I just a naive implementation for matrix multiply. But if you're just trying to have fun, then have fun :)

**Comment by tedsta** [comment]
This should be fixed now
