### ISSUE TITLE
can it run fast? faster then c/c++ or not?

### ISSUE THREAD

**Issue by supermanmsc** [tedsta/deeplearn-rs#7]

**Comment by tedsta** [comment]
Hi, at this point this is mostly just for education (I haven't and don't plan to publish it on crates.io). It is not fast, the OpenCL kernels it uses are naive implementations ([see here for crazy things you can do to optimize matrix multiplication on GPU](https://cnugteren.github.io/tutorial/pages/page1.html)). If you are building a real-world product I'd go with pytorch or tensorflow.
